version: 2.1

jobs:
  build:
    docker:
      - image: haskell:8.8.3
    steps:
      - checkout
      - run:
          name: Test
          command: stack test --system-ghc
      - run:
          name: Build
          command: stack build --system-ghc --local-bin-path=. --copy-bins
